### ISSUE TITLE
Dash attack cannot activate when near wall

### ISSUE THREAD

**Issue by motlevelone** [GameLevelOne/JavataleIssues#116] opened 2018-10-19 07:36 UTC
Steps:
1. Face close to wall or map edges
2. Use Dash attack

Expected:
Still charging dash and then bounced

v0.0.25

**Comment by BhaktiGL1** [comment] 2018-10-19 11:17
The bug cannot reproduce, maybe because the player does not has enough mana to use boots

**Comment by BhaktiGL1** [comment] 2018-10-22 17:45
Fixed in version v0.0.27

**Comment by GL1Elwin** [comment] 2018-10-24 02:54
checked in v28

**Closed as completed by GL1Elwin** 2018-10-24 02:54 UTC
Labels: bug, not reproducable, 3 - if possible fix
